### ISSUE TITLE
TypeError: Object.keys called on non-object

### ISSUE THREAD

**Issue by ryan-roemer** [niki4810/gulp-devtools#1]
Hi @niki4810 !

`npm` installed locally with `PATH` enhancement. Got this:

```
$ gulp-devtools 
gulp.env has been deprecated. Use your own CLI parser instead. We recommend using optimist or minimist.

/Users/rroemer/scm/fmd/training/node_modules/gulp-devtools/lib/gulp-devtools.js:13
  var gulpTasks = Object.keys(gulpFile.tasks).sort();
                         ^
TypeError: Object.keys called on non-object
    at Function.keys (native)
    at Object.gulpDevTools [as init] (/Users/rroemer/scm/fmd/training/node_modules/gulp-devtools/lib/gulp-devtools.js:13:26)
    at Object.<anonymous> (/Users/rroemer/scm/fmd/training/node_modules/gulp-devtools/bin/gulp-devtools.js:3:5)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
```

**Comment by ryan-roemer** [comment]
So.... reading the documentation would really help me. One

``` js
module.exports = gulp;
```

... and I'm up!
