### ISSUE TITLE
Cannot find gulp-devtools

### ISSUE THREAD

**Issue by kevinSuttle** [niki4810/gulp-devtools#4]
```
❯ gulp-devtools

module.js:340
    throw err;
    ^
Error: Cannot find module 'gulp-devtools'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/kevinsuttle/Code/myapp/gulpfile.js:6:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

❯ gulp -v
[gulp] CLI version 3.6.0
[gulp] Local version 3.6.2
```

OS X 10.9.3
npm 1.4.10
node 0.10.28

**Comment by niki4810** [comment]
@kevinSuttle  I did a little sanity checked on my mac, see the image below. Everything seems to work fine for me. 

![gulp-devtools-i1](https://cloud.githubusercontent.com/assets/1467801/3139785/8843be0c-e8f0-11e3-862d-869e15d57278.gif)

can you clear your npm cache and try it again, I am guessing this issue could be local to your mac.

**Comment by kevinSuttle** [comment]
Clearing the cache did it. I also think I may have required gulp-devtools in my gulpfile previously out of habit. Thanks!
